name: Windows Canary Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '8.0.x' # Change this to your desired .NET version

    - name: Restore dependencies
      run: dotnet restore src/windows/MathBotCLI.csproj

    - name: Build
      run: dotnet build src/windows/MathBotCLI.csproj --configuration Release --output "canary/Windows/"

    - name: Set Git identity
      run: |
        git config user.email "danielmcguire23@icloud.com"
        git config user.name "Daniel McGuire"

    - name: Add ignored files (.gitignore)
      run: |
        git add -f canary/Windows/*
        git commit -m "Built Windows Canary"
        git push
